DROP TABLE trecho_intervencao CASCADE CONSTRAINTS;

DROP TABLE relatorio_prioridade CASCADE CONSTRAINTS;

DROP TABLE intervencao_operacional CASCADE CONSTRAINTS;

DROP TABLE equipe_membro CASCADE CONSTRAINTS;

DROP TABLE trechos_rodovia CASCADE CONSTRAINTS;

DROP TABLE pessoas CASCADE CONSTRAINTS;

DROP TABLE equipes_manutencao CASCADE CONSTRAINTS;

CREATE TABLE equipes_manutencao (
    id_equipe NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2 (80) NOT NULL,
    descricao VARCHAR2 (200)
);

CREATE TABLE pessoas (
    documento VARCHAR2 (20) PRIMARY KEY,
    nome VARCHAR2 (100) NOT NULL,
    data_nascimento DATE NOT NULL
);

CREATE TABLE equipe_membro (
    id_equipe NUMBER NOT NULL,
    documento VARCHAR2 (20) NOT NULL,
    PRIMARY KEY (id_equipe, documento),
    CONSTRAINT fk_equipe_membro_equipe FOREIGN KEY (id_equipe) REFERENCES equipes_manutencao (id_equipe),
    CONSTRAINT fk_equipe_membro_pessoa FOREIGN KEY (documento) REFERENCES pessoas (documento)
);

CREATE TABLE trechos_rodovia (
    id_trecho NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_trecho VARCHAR2 (120) NOT NULL,
    km_inicial NUMBER (6, 2) NOT NULL,
    km_final NUMBER (6, 2) NOT NULL,
    nivel_vegetacao_cm NUMBER (6, 2) NOT NULL CHECK (nivel_vegetacao_cm >= 0),
    tipo_trecho VARCHAR2 (20) NOT NULL CHECK (
        tipo_trecho IN ('SECO', 'UMIDO')
    ),
    monitoravel_iot NUMBER (1) DEFAULT 0 CHECK (monitoravel_iot IN (0, 1)),
    id_equipe NUMBER,
    CONSTRAINT fk_trecho_equipe FOREIGN KEY (id_equipe) REFERENCES equipes_manutencao (id_equipe),
    CONSTRAINT chk_trecho_km CHECK (km_final > km_inicial)
);

CREATE TABLE intervencao_operacional (
    id_intervencao NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2 (50) NOT NULL UNIQUE,
    descricao VARCHAR2 (200)
);

CREATE TABLE trecho_intervencao (
    id_trecho NUMBER NOT NULL,
    id_intervencao NUMBER NOT NULL,
    data_programada DATE DEFAULT SYSDATE,
    observacao VARCHAR2 (220),
    PRIMARY KEY (id_trecho, id_intervencao),
    CONSTRAINT fk_trecho_interv_trecho FOREIGN KEY (id_trecho) REFERENCES trechos_rodovia (id_trecho),
    CONSTRAINT fk_trecho_interv_interv FOREIGN KEY (id_intervencao) REFERENCES intervencao_operacional (id_intervencao)
);

CREATE TABLE relatorio_prioridade (
    id_relatorio NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    qt_urgente NUMBER (3) NOT NULL,
    qt_critico NUMBER (3) NOT NULL,
    qt_atencao NUMBER (3) NOT NULL,
    qt_normal NUMBER (3) NOT NULL,
    resumo VARCHAR2 (500),
    data_geracao DATE DEFAULT SYSDATE
);

CREATE INDEX idx_trecho_tipo ON trechos_rodovia (tipo_trecho);

CREATE INDEX idx_trecho_vegetacao ON trechos_rodovia (nivel_vegetacao_cm);